---
name: Test-Run-Plugin-AlternateInterpreters
version: 0.0109
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
abstract: Define different interpreters for different test scripts with Test::Run.
license: mit
resources:
  license: http://www.opensource.org/licenses/mit-license.php
requires:
  MRO::Compat: 0
  Test::Run::CmdLine: 0.0111
  Test::Run::Core: 0.0118
  YAML: 0
build_requires:
  Test::More: 0
  Test::Run::CmdLine::Trap::ProveApp: 0
  Test::Trap: 0
provides:
  Test::Run::CmdLine::Plugin::AlternateInterpreters:
    file: lib/Test/Run/CmdLine/Plugin/AlternateInterpreters.pm
    version: 0.0102
  Test::Run::Plugin::AlternateInterpreters:
    file: lib/Test/Run/Plugin/AlternateInterpreters.pm
    version: 0.0109
  Test::Run::Plugin::AlternateInterpreters::Straps::AltIntrPlugin:
    file: lib/Test/Run/Plugin/AlternateInterpreters/Straps/AltIntrPlugin.pm
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
