---
name: Test-Run-Plugin-AlternateInterpreters
version: 0.01
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
abstract: Define different interpreters for different test scripts with Test::Run.
license: mit
resources:
  license: http://opensource.org/licenses/mit-license.php
build_requires:
  Test::More: 0
provides:
  Test::Run::CmdLine::Plugin::AlternateInterpreters:
    file: lib/Test/Run/CmdLine/Plugin/AlternateInterpreters.pm
    version: 0.0100
  Test::Run::Plugin::AlternateInterpreters:
    file: lib/Test/Run/Plugin/AlternateInterpreters.pm
    version: 0.01
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
