---
name: Test-Run-Plugin-AlternateInterpreters
version: 0.0120
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
abstract: Define different interpreters for different test scripts with Test::Run.
license: mit
resources:
  license: http://www.opensource.org/licenses/mit-license.php
build_requires:
  Test::More: 0
  Test::Run::CmdLine::Trap::ProveApp: 0
  Test::Trap: 0
requires:
  MRO::Compat: 0
  Moose: 0
  Test::Run::CmdLine: 0.0120
  Test::Run::Core: 0.0120
configure_requires:
  Module::Build: 0.34
provides:
  Test::Run::CmdLine::Plugin::AlternateInterpreters:
    file: lib/Test/Run/CmdLine/Plugin/AlternateInterpreters.pm
    version: 0.0120
  Test::Run::Plugin::AlternateInterpreters:
    file: lib/Test/Run/Plugin/AlternateInterpreters.pm
    version: 0.0120
  Test::Run::Plugin::AlternateInterpreters::Straps::AltIntrPlugin:
    file: lib/Test/Run/Plugin/AlternateInterpreters/Straps/AltIntrPlugin.pm
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
