---
abstract: 'Define different interpreters for different test scripts with Test::Run.'
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  Test::More: 0
  Test::Run::CmdLine::Trap::ProveApp: 0
  Test::Trap: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Run-Plugin-AlternateInterpreters
provides:
  Test::Run::CmdLine::Plugin::AlternateInterpreters:
    file: lib/Test/Run/CmdLine/Plugin/AlternateInterpreters.pm
    version: 0.0121
  Test::Run::Plugin::AlternateInterpreters:
    file: lib/Test/Run/Plugin/AlternateInterpreters.pm
    version: 0.0121
  Test::Run::Plugin::AlternateInterpreters::Straps::AltIntrPlugin:
    file: lib/Test/Run/Plugin/AlternateInterpreters/Straps/AltIntrPlugin.pm
requires:
  MRO::Compat: 0
  Moose: 0
  Test::Run::CmdLine: 0.0120
  Test::Run::Core: 0.0120
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: 0.0121
